---
  :verbose: false
  :concurrency: 4
  :pidfile: tmp/pids/sidekiq.pid
  :queues:
    - mi_classrooms_development_default
    - mi_classrooms_staging_default
    - mi_classrooms_production_default

  production:
    :concurrency: 25

  staging:
    :concurrency: 25